CLASS_VEHICLE='0'; CLASS_HUMAN='1'; CLASS_UAP='2'; CLASS_UAI='3'
VALID_CLASSES={CLASS_VEHICLE,CLASS_HUMAN,CLASS_UAP,CLASS_UAI}
LANDING_NOT_APPLICABLE='-1'; LANDING_UNSUITABLE='0'; LANDING_SUITABLE='1'
VALID_LANDING={LANDING_NOT_APPLICABLE,LANDING_UNSUITABLE,LANDING_SUITABLE}
MOTION_NOT_APPLICABLE='-1'; MOTION_STATIONARY='0'; MOTION_MOVING='1'
VALID_MOTION={MOTION_NOT_APPLICABLE,MOTION_STATIONARY,MOTION_MOVING}
FIELD_ID='id'; FIELD_USER='user'; FIELD_FRAME='frame'; FIELD_OBJECTS='detected_objects'; FIELD_TRANSLATIONS='detected_translations'; FIELD_UNDEFINED='detected_undefined_objects'
